//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pub_n_Fun.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerOpinions
    {
        public int opinionID { get; set; }
        public Nullable<int> pubID { get; set; }
        public Nullable<float> rating { get; set; }
        public int customerId { get; set; }
        public string opinion { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual Pubs Pubs { get; set; }
    }
}
