//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pub_n_Fun.EDM
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Pub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pub()
        {
            this.customerOpinions = new HashSet<customerOpinion>();
        }

        [DataMember]
        public int pubID { get; set; }
        [DataMember]
        public string address { get; set; }
        [DataMember]
        public Nullable<int> customerOverallRatings { get; set; }
        [DataMember]
        public string name { get; set; }
        [DataMember]
        public Nullable<float> longitude { get; set; }
        [DataMember]
        public Nullable<float> latitude { get; set; }

        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerOpinion> customerOpinions { get; set; }
    }
}
