//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pub_n_Fun.EDM.qwe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rftkocsmadbEntities3 : DbContext
    {
        public rftkocsmadbEntities3()
            : base("name=rftkocsmadbEntities00")
        {
            Configuration.ProxyCreationEnabled=false;
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pubs> Pubs { get; set; }
        public virtual DbSet<customerOpinions> customerOpinions { get; set; }
    }
}
